-- Creates the database hbtn_0d_usa and the table cities in hbtn_0d_usa database
-- cities will have id IN, state_id INT and name VARCHAR(256)
-- values of those rows are (autogenerated, reference to id, just not NULL)
-- if they already exists just ignore

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (
       id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
       state_id INT NOT NULL,
       FOREIGN KEY (state_id) REFERENCES states(id),
       name VARCHAR(256) NOT NULL
);
